/* Vergi Takvimim: tüm kullanıcı tercihleri yalnızca bu cihazdaki LocalStorage'da tutulur. */
const $ = (s, e = document) => e.querySelector(s);
const depolama = { al: (a, varsayilan) => { try { return JSON.parse(localStorage.getItem(a)) ?? varsayilan; } catch { return varsayilan; } }, yaz: (a, v) => localStorage.setItem(a, JSON.stringify(v)) };
const durum = { sayfa: 'ana', veriler: [], ay: new Date().getMonth(), yil: new Date().getFullYear(), ayarlar: depolama.al('vtAyarlar', null), favoriler: depolama.al('vtFavoriler', []), tamamlananlar: depolama.al('vtTamamlananlar', []) };
const ayAdlari = ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
const renkler = { KDV:'#2d8cff', Muhtasar:'#8d64e8', 'Geçici Vergi':'#f09b3f', Kurumlar:'#ec5a7d', Gelir:'#12a78a', Damga:'#e36d42', 'e-Defter':'#33a16d', SGK:'#5886c5' };

async function jsonOku(dosya) {
  try { const yanit = await fetch(`data/${dosya}`, { cache: 'no-cache' }); if (!yanit.ok) throw Error(`HTTP ${yanit.status}`); return { veri: await yanit.json(), hata: false }; }
  catch { return { veri: [], hata: true }; }
}
async function baslat() {
  const [vergiler, odemeler, edefterAylik, edefterUcaylik, son] = await Promise.all(['vergiler.json','odemeler.json','edefter_aylik.json','edefter_ucaylik.json','last-update.json'].map(jsonOku));
  const edefter = durum.ayarlar?.edefter === 'ucaylik' ? edefterUcaylik.veri : edefterAylik.veri;
  durum.veriHatasi = [vergiler, odemeler, edefterAylik, edefterUcaylik, son].some(x => x.hata);
  durum.veriler = [...vergiler.veri, ...odemeler.veri, ...edefter]; durum.sonGuncelleme = son.veri.tarih || son.veri.date || 'Bilgi alınamadı';
  document.body.classList.toggle('koyu', depolama.al('vtTema', 'acik') === 'koyu');
  if (!durum.ayarlar) kurulumSihirbazi(); else ekranCiz(); bildirimKontrol();
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js');
}
function tarih(islem) { return new Date(`${islem.tarih}T12:00:00`); }
function kalanGun(islem) { return Math.ceil((tarih(islem) - new Date(new Date().toDateString())) / 86400000); }
function tamamlandiMi(i) { return durum.tamamlananlar.includes(i.id); }
function islemSatiri(i) { const gun = kalanGun(i), tam = tamamlandiMi(i), fav = durum.favoriler.includes(i.id); return `<article class="kart islem ${tam ? 'tamamlandi' : ''}"><i class="renk" style="background:${renkler[i.kategori] || '#1463d9'}"></i><div class="islem-bilgi"><b>${i.ad}</b><span class="soluk">${new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long'}).format(tarih(i))} · ${i.aciklama || i.kategori}</span></div><span class="etiket">${i.kategori}</span><button class="yildiz" data-favori="${i.id}" aria-label="Favori">${fav ? '★' : '☆'}</button><button class="kalan ${gun < 0 ? 'gecikmis':''}" data-tamamla="${i.id}">${tam ? '✓' : gun < 0 ? `${Math.abs(gun)} gün geçti` : gun === 0 ? 'Bugün' : `${gun} gün`}</button></article>`; }
function seciliIslemler() { return durum.veriler.filter(i => !tamamlandiMi(i)).sort((a,b) => tarih(a)-tarih(b)); }
function ekranCiz() { const baslik = {ana:'Vergi Takvimim',yaklasan:'Yaklaşanlar',takvim:'Vergi Takvimi',odemeler:'Ödemeler',ayarlar:'Ayarlar'}[durum.sayfa]; const uyarı = durum.veriHatasi ? '<section class="kart"><b>Veriler yüklenemedi</b><p class="soluk">İnternet bağlantısını kontrol edin. Varsa cihazdaki son çevrimdışı veriler kullanılmaya devam eder.</p></section>' : ''; $('#sayfa-baslik').textContent = baslik; $('#icerik').innerHTML = uyarı + ({ ana: anaSayfa, yaklasan: listeSayfa, takvim: takvimSayfa, odemeler: odemeSayfa, ayarlar: ayarlarSayfa })[durum.sayfa](); $$('.alt-menu button').forEach(b=>b.classList.toggle('secili',b.dataset.sayfa===durum.sayfa)); olayBagla(); }
function $$(s,e=document){return [...e.querySelectorAll(s)]}
function anaSayfa() { const aktif=seciliIslemler(), bugun=aktif.filter(i=>kalanGun(i)===0).length, gecik=aktif.filter(i=>kalanGun(i)<0).length, yak=aktif.filter(i=>kalanGun(i)>0&&kalanGun(i)<=7).length, tamam=durum.tamamlananlar.length; return `<section class="hero"><p>Bugünün özeti</p><h2>${durum.ayarlar.firma} için her şey kontrol altında.</h2><span>Son veri güncellemesi: ${durum.sonGuncelleme}</span></section><section class="istatistikler"><div class="istatistik"><b>${bugun}</b><span class="kucuk">Bugün</span></div><div class="istatistik"><b>${yak}</b><span class="kucuk">Yaklaşan</span></div><div class="istatistik"><b>${gecik}</b><span class="kucuk">Geciken</span></div><div class="istatistik"><b>${tamam}</b><span class="kucuk">Tamamlanan</span></div></section><div class="bolum-baslik"><h2>Öncelikli işler</h2><button class="dugme ikincil" data-sayfa="yaklasan">Tümü</button></div>${aktif.slice(0,3).map(islemSatiri).join('') || '<p class="bos-durum">Takip edilecek işlem yok.</p>'}<div class="bolum-baslik"><h2>Hızlı erişim</h2></div><div class="liste-dugmeler">${[['◷','Yaklaşanlar','yaklasan'],['▦','Vergi Takvimi','takvim'],['▣','e-Defter','yaklasan'],['₺','Ödemeler','odemeler'],['★','Favoriler','yaklasan'],['⚙','Ayarlar','ayarlar']].map(x=>`<button class="kart menu-kart" data-sayfa="${x[2]}"><span>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div>`; }
function listeSayfa() { return `<div class="araclar"><input id="arama" placeholder="İşlem ara..."><select id="kategori-filtre"><option value="">Tüm kategoriler</option>${[...new Set(durum.veriler.map(i=>i.kategori))].map(k=>`<option>${k}</option>`).join('')}</select></div><div id="liste">${listeCiz(seciliIslemler())}</div>`; }
function listeCiz(liste) { return liste.length ? liste.map(islemSatiri).join('') : '<p class="bos-durum">Bu ölçüte uygun işlem bulunamadı.</p>'; }
function odemeSayfa(){return `<div class="araclar"><input id="arama" placeholder="Ödeme ara..."></div><div id="liste">${listeCiz(seciliIslemler().filter(i=>i.tur==='odeme'))}</div>`}
function takvimSayfa() { const ilk=new Date(durum.yil,durum.ay,1), son=new Date(durum.yil,durum.ay+1,0).getDate(), bas=(ilk.getDay()+6)%7; let gunler=''.padEnd(bas,' ').split('').map(()=>'<div class="gun bos"></div>').join(''); for(let g=1;g<=son;g++){const gunIslem=durum.veriler.filter(i=>{const t=tarih(i);return t.getDate()===g&&t.getMonth()===durum.ay&&t.getFullYear()===durum.yil});const bugun=new Date();gunler+=`<button class="gun ${g===bugun.getDate()&&durum.ay===bugun.getMonth()&&durum.yil===bugun.getFullYear()?'bugun':''}" data-gun="${g}">${g}<br>${gunIslem.slice(0,3).map(i=>`<i class="nokta" style="background:${renkler[i.kategori]||'#1463d9'}"></i>`).join('')}</button>`}return `<div class="takvim-baslik"><button class="dugme ikincil" data-ay="-1">‹</button><h2>${ayAdlari[durum.ay]} ${durum.yil}</h2><button class="dugme ikincil" data-ay="1">›</button></div><div class="hafta"><span>Pzt</span><span>Sal</span><span>Çar</span><span>Per</span><span>Cum</span><span>Cmt</span><span>Paz</span></div><div class="gunler">${gunler}</div><p class="soluk" style="margin-top:16px">Renkli noktalar o güne ait beyan, ödeme ve e-Defter işlemlerini gösterir.</p>`; }
function ayarlarSayfa(){const a=durum.ayarlar;return `<section class="kart form-grid"><label>Firma adı<input id="firma" value="${a.firma}"></label><label>Şirket türü<select id="sirket"><option ${a.sirket==='Ltd. Şti.'?'selected':''}>Ltd. Şti.</option><option ${a.sirket==='Şahıs İşletmesi'?'selected':''}>Şahıs İşletmesi</option><option ${a.sirket==='A.Ş.'?'selected':''}>A.Ş.</option></select></label><label>KDV dönemi<select id="kdv"><option value="aylik" ${a.kdv==='aylik'?'selected':''}>Aylık</option><option value="ucaylik" ${a.kdv==='ucaylik'?'selected':''}>3 Aylık</option></select></label><label>e-Defter dönemi<select id="edefter"><option value="aylik" ${a.edefter==='aylik'?'selected':''}>Aylık</option><option value="ucaylik" ${a.edefter==='ucaylik'?'selected':''}>3 Aylık</option></select></label><label><input type="checkbox" id="bildirim-acik" ${a.bildirim?'checked':''}> Bildirimler açık</label><label>Hatırlatma<select id="hatirlatma"><option>1</option><option ${a.hatirlatma===3?'selected':''}>3</option><option ${a.hatirlatma===7?'selected':''}>7</option></select></label><button class="dugme" id="ayarlari-kaydet">Ayarları kaydet</button><button class="dugme ikincil" id="bildirim-izin">Bildirim izni iste</button><button class="dugme ikincil" id="veri-sifirla">Tüm yerel verileri sıfırla</button></section>`}
function olayBagla(){ $$('[data-sayfa]').forEach(b=>b.onclick=()=>{durum.sayfa=b.dataset.sayfa;ekranCiz()}); $$('[data-favori]').forEach(b=>b.onclick=()=>{const id=b.dataset.favori;durum.favoriler=durum.favoriler.includes(id)?durum.favoriler.filter(x=>x!==id):[...durum.favoriler,id];depolama.yaz('vtFavoriler',durum.favoriler);ekranCiz()}); $$('[data-tamamla]').forEach(b=>b.onclick=()=>{const id=b.dataset.tamamla;durum.tamamlananlar=tamamlandiMi(id)?durum.tamamlananlar.filter(x=>x!==id):[...durum.tamamlananlar,id];depolama.yaz('vtTamamlananlar',durum.tamamlananlar);ekranCiz()}); $$('[data-ay]').forEach(b=>b.onclick=()=>{durum.ay+=+b.dataset.ay;if(durum.ay<0){durum.ay=11;durum.yil--}if(durum.ay>11){durum.ay=0;durum.yil++}ekranCiz()}); $$('.gun[data-gun]').forEach(b=>b.onclick=()=>gunModal(+b.dataset.gun)); const arama=$('#arama');if(arama)arama.oninput=filtrele;const filtre=$('#kategori-filtre');if(filtre)filtre.onchange=filtrele;$('#ayarlari-kaydet')?.addEventListener('click',ayarKaydet);$('#bildirim-izin')?.addEventListener('click',()=>Notification.requestPermission().then(()=>mesaj('Bildirim tercihi güncellendi.')));$('#veri-sifirla')?.addEventListener('click',()=>{if(confirm('Tüm tercihler ve işaretlemeler silinsin mi?')){localStorage.clear();location.reload()}})}
function filtrele(){const q=$('#arama').value.toLocaleLowerCase('tr'),k=$('#kategori-filtre')?.value||'';let l=seciliIslemler().filter(i=>(i.ad+i.kategori).toLocaleLowerCase('tr').includes(q)&&(!k||i.kategori===k));if(durum.sayfa==='odemeler')l=l.filter(i=>i.tur==='odeme');$('#liste').innerHTML=listeCiz(l)}
function gunModal(g){const l=durum.veriler.filter(i=>tarih(i).getDate()===g&&tarih(i).getMonth()===durum.ay&&tarih(i).getFullYear()===durum.yil);$('#modal-katmani').innerHTML=`<div class="modal"><section class="modal-kutu"><h2>${g} ${ayAdlari[durum.ay]}</h2><div style="margin-top:15px">${listeCiz(l)}</div><div class="modal-alt"><button class="dugme" id="modal-kapat">Kapat</button></div></section></div>`;$('#modal-kapat').onclick=()=>$('#modal-katmani').innerHTML=''}
function kurulumSihirbazi(){$('#modal-katmani').innerHTML=`<div class="modal"><section class="modal-kutu"><p class="kucuk">İLK KURULUM</p><h2 style="margin:5px 0 18px">Vergi Takvimim'e hoş geldiniz</h2><div class="form-grid"><label>Firma adı<input id="w-firma" placeholder="Örn. Örnek Ticaret Ltd."></label><label>Vergi numarası<input id="w-vergi" inputmode="numeric" placeholder="10 haneli vergi numarası"></label><label>Şirket türü<select id="w-sirket"><option>Ltd. Şti.</option><option>Şahıs İşletmesi</option><option>A.Ş.</option></select></label><label>KDV dönemi<select id="w-kdv"><option value="aylik">Aylık</option><option value="ucaylik">3 Aylık</option></select></label><label>e-Defter dönemi<select id="w-edefter"><option value="aylik">Aylık</option><option value="ucaylik">3 Aylık</option></select></label><label><input id="w-bildirim" type="checkbox" checked> Hatırlatma bildirimleri açık</label><label>Kaç gün önce hatırlatalım?<select id="w-hatirlatma"><option value="1">1 gün</option><option value="3" selected>3 gün</option><option value="7">7 gün</option></select></label></div><div class="modal-alt"><button class="dugme" id="kurulum-kaydet">Başlayalım</button></div></section></div>`;$('#kurulum-kaydet').onclick=()=>{const firma=$('#w-firma').value.trim();if(!firma)return mesaj('Lütfen firma adını girin.');durum.ayarlar={firma,vergi:$('#w-vergi').value.trim(),sirket:$('#w-sirket').value,kdv:$('#w-kdv').value,edefter:$('#w-edefter').value,bildirim:$('#w-bildirim').checked,hatirlatma:+$('#w-hatirlatma').value};depolama.yaz('vtAyarlar',durum.ayarlar);$('#modal-katmani').innerHTML='';ekranCiz()}}
function ayarKaydet(){durum.ayarlar={...durum.ayarlar,firma:$('#firma').value.trim()||'Firmam',sirket:$('#sirket').value,kdv:$('#kdv').value,edefter:$('#edefter').value,bildirim:$('#bildirim-acik').checked,hatirlatma:+$('#hatirlatma').value};depolama.yaz('vtAyarlar',durum.ayarlar);mesaj('Ayarlar kaydedildi. e-Defter verisi yenilemede uygulanır.');ekranCiz()}
function mesaj(m){const e=$('#bildirim');e.textContent=m;e.classList.add('goster');setTimeout(()=>e.classList.remove('goster'),3000)}
function bildirimKontrol(){if(!durum.ayarlar?.bildirim||Notification.permission!=='granted')return;seciliIslemler().forEach(i=>{const g=kalanGun(i);if([0,-1,durum.ayarlar.hatirlatma].includes(g))new Notification(g<0?'Geciken vergi işlemi':g===0?'Bugün son gün':`${g} gün kaldı`,{body:i.ad})})}
$('#tema-dugmesi').onclick=()=>{const yeni=document.body.classList.toggle('koyu')?'koyu':'acik';depolama.yaz('vtTema',yeni)}; document.addEventListener('DOMContentLoaded',baslat);
